//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsActivity()
        {
            this.MsParticipants = new HashSet<MsParticipant>();
        }
    
        public int activityID { get; set; }
        public string activityTitle { get; set; }
        public string activityDescription { get; set; }
        public string activityLocation { get; set; }
        public System.DateTime activityDate { get; set; }
        public int activityCapacity { get; set; }
        public int activityCurrentParticipants { get; set; }
        public System.TimeSpan activityTime { get; set; }
        public string activityRequirements { get; set; }
        public byte[] activityImage { get; set; }
        public string activityStatus { get; set; }
        public string activityCreator { get; set; }
        public System.DateTime activityStartRegistration { get; set; }
        public System.DateTime activityEndRegistration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MsParticipant> MsParticipants { get; set; }
    }
}
