//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsArticle
    {
        public int articleID { get; set; }
        public string articleTitle { get; set; }
        public string articleAuthor { get; set; }
        public System.DateTime articleDate { get; set; }
        public System.TimeSpan articleTime { get; set; }
        public string articleSubTitle { get; set; }
        public string articleContent { get; set; }
        public byte[] articleImage { get; set; }
    }
}
