//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsUser
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public Nullable<System.DateTime> userDOB { get; set; }
        public string userAddress { get; set; }
        public string userRole { get; set; }
        public string verifStatus { get; set; }
        public byte[] userKTP { get; set; }
    }
}
